# coding: utf-8

"""
    DHL Express APIs (MyDHL API)

    Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services   In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments)   # noqa: E501

    OpenAPI spec version: 2.12.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.rating_api import RatingApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRatingApi(unittest.TestCase):
    """RatingApi unit test stubs"""

    def setUp(self):
        self.api = RatingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_exp_api_landed_cost(self):
        """Test case for exp_api_landed_cost

        Landed Cost  # noqa: E501
        """
        pass

    def test_exp_api_rates(self):
        """Test case for exp_api_rates

        Retrieve Rates for a one piece Shipment  # noqa: E501
        """
        pass

    def test_exp_api_rates_many(self):
        """Test case for exp_api_rates_many

        Retrieve Rates for Multi-piece Shipments  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
