# coding: utf-8

"""
    DHL Express APIs (MyDHL API)

    Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments)   # noqa: E501

    OpenAPI spec version: 2.7.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dhl_express_client
from dhl_express_client.models.supermodel_io_logistics_express_tracking_response_shipments import SupermodelIoLogisticsExpressTrackingResponseShipments  # noqa: E501
from dhl_express_client.rest import ApiException


class TestSupermodelIoLogisticsExpressTrackingResponseShipments(unittest.TestCase):
    """SupermodelIoLogisticsExpressTrackingResponseShipments unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSupermodelIoLogisticsExpressTrackingResponseShipments(self):
        """Test SupermodelIoLogisticsExpressTrackingResponseShipments"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.supermodel_io_logistics_express_tracking_response_shipments.SupermodelIoLogisticsExpressTrackingResponseShipments()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
