# coding: utf-8

"""
    DHL Express APIs (MyDHL API)

    Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services   In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments)   # noqa: E501

    OpenAPI spec version: 2.12.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.servicepoint_api import ServicepointApi  # noqa: E501
from swagger_client.rest import ApiException


class TestServicepointApi(unittest.TestCase):
    """ServicepointApi unit test stubs"""

    def setUp(self):
        self.api = ServicepointApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_exp_api_servicepoints(self):
        """Test case for exp_api_servicepoints

        Returns list of service points based on the given postal location address, service point ID or geocode details for DHL Express Service points to pick-up and drop-off shipments  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
