# coding: utf-8

"""
    DHL Express APIs (MyDHL API)

    Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services   In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments)   # noqa: E501

    OpenAPI spec version: 2.12.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SupermodelIoLogisticsExpressCreateShipmentResponseCustomerDetailsShipperDetails(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'postal_address': 'SupermodelIoLogisticsExpressAddressCreateShipmentResponse',
        'contact_information': 'SupermodelIoLogisticsExpressContactCreateShipmentResponse'
    }

    attribute_map = {
        'postal_address': 'postalAddress',
        'contact_information': 'contactInformation'
    }

    def __init__(self, postal_address=None, contact_information=None):  # noqa: E501
        """SupermodelIoLogisticsExpressCreateShipmentResponseCustomerDetailsShipperDetails - a model defined in Swagger"""  # noqa: E501
        self._postal_address = None
        self._contact_information = None
        self.discriminator = None
        if postal_address is not None:
            self.postal_address = postal_address
        if contact_information is not None:
            self.contact_information = contact_information

    @property
    def postal_address(self):
        """Gets the postal_address of this SupermodelIoLogisticsExpressCreateShipmentResponseCustomerDetailsShipperDetails.  # noqa: E501


        :return: The postal_address of this SupermodelIoLogisticsExpressCreateShipmentResponseCustomerDetailsShipperDetails.  # noqa: E501
        :rtype: SupermodelIoLogisticsExpressAddressCreateShipmentResponse
        """
        return self._postal_address

    @postal_address.setter
    def postal_address(self, postal_address):
        """Sets the postal_address of this SupermodelIoLogisticsExpressCreateShipmentResponseCustomerDetailsShipperDetails.


        :param postal_address: The postal_address of this SupermodelIoLogisticsExpressCreateShipmentResponseCustomerDetailsShipperDetails.  # noqa: E501
        :type: SupermodelIoLogisticsExpressAddressCreateShipmentResponse
        """

        self._postal_address = postal_address

    @property
    def contact_information(self):
        """Gets the contact_information of this SupermodelIoLogisticsExpressCreateShipmentResponseCustomerDetailsShipperDetails.  # noqa: E501


        :return: The contact_information of this SupermodelIoLogisticsExpressCreateShipmentResponseCustomerDetailsShipperDetails.  # noqa: E501
        :rtype: SupermodelIoLogisticsExpressContactCreateShipmentResponse
        """
        return self._contact_information

    @contact_information.setter
    def contact_information(self, contact_information):
        """Sets the contact_information of this SupermodelIoLogisticsExpressCreateShipmentResponseCustomerDetailsShipperDetails.


        :param contact_information: The contact_information of this SupermodelIoLogisticsExpressCreateShipmentResponseCustomerDetailsShipperDetails.  # noqa: E501
        :type: SupermodelIoLogisticsExpressContactCreateShipmentResponse
        """

        self._contact_information = contact_information

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SupermodelIoLogisticsExpressCreateShipmentResponseCustomerDetailsShipperDetails, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SupermodelIoLogisticsExpressCreateShipmentResponseCustomerDetailsShipperDetails):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
