# coding: utf-8

"""
    DHL Express APIs (MyDHL API)

    Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services   In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments)   # noqa: E501

    OpenAPI spec version: 2.12.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SupermodelIoLogisticsExpressDeliveryOptionsResponseParameters(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'is_required': 'bool',
        'accepted_values': 'list[str]'
    }

    attribute_map = {
        'name': 'name',
        'is_required': 'isRequired',
        'accepted_values': 'acceptedValues'
    }

    def __init__(self, name=None, is_required=None, accepted_values=None):  # noqa: E501
        """SupermodelIoLogisticsExpressDeliveryOptionsResponseParameters - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._is_required = None
        self._accepted_values = None
        self.discriminator = None
        self.name = name
        self.is_required = is_required
        if accepted_values is not None:
            self.accepted_values = accepted_values

    @property
    def name(self):
        """Gets the name of this SupermodelIoLogisticsExpressDeliveryOptionsResponseParameters.  # noqa: E501

        delivery option parameter name\"  # noqa: E501

        :return: The name of this SupermodelIoLogisticsExpressDeliveryOptionsResponseParameters.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SupermodelIoLogisticsExpressDeliveryOptionsResponseParameters.

        delivery option parameter name\"  # noqa: E501

        :param name: The name of this SupermodelIoLogisticsExpressDeliveryOptionsResponseParameters.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def is_required(self):
        """Gets the is_required of this SupermodelIoLogisticsExpressDeliveryOptionsResponseParameters.  # noqa: E501


        :return: The is_required of this SupermodelIoLogisticsExpressDeliveryOptionsResponseParameters.  # noqa: E501
        :rtype: bool
        """
        return self._is_required

    @is_required.setter
    def is_required(self, is_required):
        """Sets the is_required of this SupermodelIoLogisticsExpressDeliveryOptionsResponseParameters.


        :param is_required: The is_required of this SupermodelIoLogisticsExpressDeliveryOptionsResponseParameters.  # noqa: E501
        :type: bool
        """
        if is_required is None:
            raise ValueError("Invalid value for `is_required`, must not be `None`")  # noqa: E501

        self._is_required = is_required

    @property
    def accepted_values(self):
        """Gets the accepted_values of this SupermodelIoLogisticsExpressDeliveryOptionsResponseParameters.  # noqa: E501

        Returned only for type=signatureRelease  # noqa: E501

        :return: The accepted_values of this SupermodelIoLogisticsExpressDeliveryOptionsResponseParameters.  # noqa: E501
        :rtype: list[str]
        """
        return self._accepted_values

    @accepted_values.setter
    def accepted_values(self, accepted_values):
        """Sets the accepted_values of this SupermodelIoLogisticsExpressDeliveryOptionsResponseParameters.

        Returned only for type=signatureRelease  # noqa: E501

        :param accepted_values: The accepted_values of this SupermodelIoLogisticsExpressDeliveryOptionsResponseParameters.  # noqa: E501
        :type: list[str]
        """

        self._accepted_values = accepted_values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SupermodelIoLogisticsExpressDeliveryOptionsResponseParameters, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SupermodelIoLogisticsExpressDeliveryOptionsResponseParameters):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
