# coding: utf-8

"""
    DHL Express APIs (MyDHL API)

    Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments)   # noqa: E501

    OpenAPI spec version: 2.7.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SupermodelIoLogisticsExpressUploadInvoiceDataResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'warnings': 'list[str]',
        'status': 'str'
    }

    attribute_map = {
        'warnings': 'warnings',
        'status': 'status'
    }

    def __init__(self, warnings=None, status=None):  # noqa: E501
        """SupermodelIoLogisticsExpressUploadInvoiceDataResponse - a model defined in Swagger"""  # noqa: E501
        self._warnings = None
        self._status = None
        self.discriminator = None
        if warnings is not None:
            self.warnings = warnings
        if status is not None:
            self.status = status

    @property
    def warnings(self):
        """Gets the warnings of this SupermodelIoLogisticsExpressUploadInvoiceDataResponse.  # noqa: E501


        :return: The warnings of this SupermodelIoLogisticsExpressUploadInvoiceDataResponse.  # noqa: E501
        :rtype: list[str]
        """
        return self._warnings

    @warnings.setter
    def warnings(self, warnings):
        """Sets the warnings of this SupermodelIoLogisticsExpressUploadInvoiceDataResponse.


        :param warnings: The warnings of this SupermodelIoLogisticsExpressUploadInvoiceDataResponse.  # noqa: E501
        :type: list[str]
        """

        self._warnings = warnings

    @property
    def status(self):
        """Gets the status of this SupermodelIoLogisticsExpressUploadInvoiceDataResponse.  # noqa: E501

        Status description  # noqa: E501

        :return: The status of this SupermodelIoLogisticsExpressUploadInvoiceDataResponse.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this SupermodelIoLogisticsExpressUploadInvoiceDataResponse.

        Status description  # noqa: E501

        :param status: The status of this SupermodelIoLogisticsExpressUploadInvoiceDataResponse.  # noqa: E501
        :type: str
        """

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SupermodelIoLogisticsExpressUploadInvoiceDataResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SupermodelIoLogisticsExpressUploadInvoiceDataResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
